version: '3.8' # Make sure to specify the version

services: # Corrected from "service" to "services"
  postgres:
    container_name: postgres-sql-bsn
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: book_social_network
    volumes:
      - postgres:/var/lib/postgresql/data # Corrected to specify mount target
    ports:
      - "5432:5432"
    networks:
      - spring-demo

  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - spring-demo

networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local
